### PR TITLE
Remove TestGenerateSeed Funcs from business tests

### PR DESCRIPTION
**Pull request by Ali-Farhadnia**
I've made some changes to test functions in business layer for better readability. Here's why:

Consistency: I've used the same method for seeding data in all tests, which makes them easier to follow and maintain.

Clearer Tests: Putting the test data front  improves readability. It's easier to understand what each test is checking.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
I should have used my test util functions for that. I see that now. I think it's better to be testing against random data.

**Comment by Ali-Farhadnia** [comment]
Do you mean that util functions must  used for seeding the user too?

**Comment by ardan-bkennedy** [comment]
I updated the code. All tests are using the core seed data functions. We don't want to hard code anything in the tests. If you have a special need for a DB record to look a certain way, you have the ability to do that. But I would use these Test functions as a first choice.

**Comment by ardan-bkennedy** [comment]
MIssing something

**Comment by Ali-Farhadnia** [comment]
thanks bill

**Comment by ardan-bkennedy** [comment]
Look at it now. I think this is better. GREAT CATCH, I missed this :(

**Comment by Ali-Farhadnia** [comment]
Thanks bill.Yes i think that is better now :)

**Pull request closed without merging**
