### PR TITLE
Refactor: Improve JSON formatting in Docker inspect template.

### PR DESCRIPTION
**Pull request by mobamoh**
Replace manual string manipulation with in-template formatting for cleaner, more efficient code.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Have you tests this with IPv6 on so docker returns 2 IP addresses and not just 1?

**Comment by ardan-bkennedy** [comment]
Also, I need you to add yourself to the contributors file please.

**Comment by mobamoh** [comment]
Hi Bill, Yes I've tested. Attached the screenshots.

**Comment by mobamoh** [comment]
> Also, I need you to add yourself to the contributors file please.

Sure! where can I find that?

**Comment by ardan-bkennedy** [comment]
It's at the root of the project. This change is awesome!

**Comment by ardan-bkennedy** [comment]
Can you please keep the CONTRIBUTORS file is alphabetical order.

**Pull request merged**
