### PR TITLE
Use declarative configuration struct in main

### PR DESCRIPTION
**Pull request by nstogner**
Example for #16. This PR uses an anonymous type in `main` as a form of making configuration more declarative. IMO this makes configuration inputs more searchable. Possible benefits include: easy exposure of configuration via a future API endpoint along with the ability to print configuration usage. The `envconfig` package is used as reference implementation... it would probably be replaced with a kit package.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
I absolutely don't want to add another dependency for this. I rather add support our cfg package.

**Comment by ardan-bkennedy** [comment]
Shit, that looks pretty nice! So that can replace our cfg package. Then we have the issue of adding cli flags.

**Comment by ardan-bkennedy** [comment]
Remove the cfg package from platform

**Comment by ardan-bkennedy** [comment]
Let's drop the PR and re-create it.

**Comment by ardan-bkennedy** [comment]
By using this new package, we lost our ability to have the config package create the flags. So I guess we need a new package that can take a config struct value and build the command line arguments?

**Comment by wyattjoh** [comment]
I know you're opposed to new packages... But this one does pretty much what you want @ardan-bkennedy: https://github.com/urfave/cli#flags

**Comment by ardan-bkennedy** [comment]
This repo has a lot of code for this. There are also two other packages it maintains :(

**Comment by ardan-bkennedy** [comment]
We must assume defaults are in use and the variables are not defined. It's the struct that defines the configuration points and defaults. It is the point of truth.

**Comment by ardan-bkennedy** [comment]
I will be closing this PR because of PR 22

https://github.com/ardanlabs/service/pull/22

**Pull request closed without merging**
